### ISSUE TITLE
addtask invalid progress

### ISSUE THREAD

**Issue by lll-jy** [AY2021S1-CS2103T-W10-3/tp#338]
The error message if I put `tp/-1`:
Progress values should only contain integers between 0 and 100 inclusive, and it should not be blank.

UG: 
Task progress is a percentage value indicating how much of the task is done

Issue: Not matching.

Error: If I put `tp/35.1`, it accepts without error.

**Comment by lucastai98** [comment]
fixed by changing the phrasing to be "value" instead of integer
